pipeline:
  #
  # publish:
  #   image: plugins/ecr
  #   when:
  #     event: tag
  #   region: us-east-1
  #   repo: 558830342743.dkr.ecr.us-east-1.amazonaws.com/faststore-ci-cd
  #   build_args: "VERSION=${DRONE_TAG##v}"
  #   tag:
  #     - ${DRONE_TAG##v}

  publish:
    image: docker.io/cguimaraes/go-ko
    when:
      event: tag
    environment:
      KO_DOCKER_REPO: 558830342743.dkr.ecr.us-east-1.amazonaws.com/knative-webhook
      GOPATH: /drone
    commands:
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 558830342743.dkr.ecr.us-east-1.amazonaws.com
    - /drone/bin/ko publish github.com/vtex/serving/cmd/webhook
  
  mark-as-latest-if-stable:
    image: plugins/webhook
    when:
      event: tag
    urls: http://releases.ingress.vtex.io/latest-if-stable/knative-webhook/${DRONE_TAG##v}
    method: PATCH
  # notify:
  #   image: plugins/slack
  #   template: "*{{Build.Status}}*: <{{Build.Link}}|{{Repo.Owner}}/{{Repo.Name}}> (${DRONE_TAG##v}) by {{Build.Author}}"
  #   webhook: https://hooks.slack.com/services/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
  #   when:
  #     event: tag
  #     status: [success, failure]